"""Derivational suffixes — a single, non-recursive derivation slot between root and inflection.

Nominal derivations (-lI, -sIz, -lIk, -CI, -CIk) turn a root/adjective into a new nominal
stem; verbal derivations (-mA, -(y)Iş, participles -(y)An/-DIk/-(y)AcAk, infinitive -mAk) turn
a verb into a nominal one. Each is data-declared: ``derivational=True`` opens a boundary (its
``name`` is recorded under ``features[tags.DERIVATION]``), ``applies_to`` is the overgeneration
guard, and the graph position handles the verb-side gating. The wiring lives in
:mod:`.transitions`.
"""

from __future__ import annotations

from ...core import tags
from .suffix import Suffix

# --- Nominal derivations (root/adj -> new nominal stem) ------------------------------
# Data-declared: each carries no inflectional feature dict — its record is the derivation
# name appended to features[tags.DERIVATION]. ``applies_to`` is the overgeneration guard.

D_LI = Suffix("li", "lI", derivational=True, to_pos=tags.ADJ, applies_to=frozenset({tags.NOUN}))
D_SIZ = Suffix("siz", "sIz", derivational=True, to_pos=tags.ADJ, applies_to=frozenset({tags.NOUN}))
D_LIK = Suffix(
    "lik",
    "lIk",
    derivational=True,
    to_pos=tags.NOUN,
    applies_to=frozenset({tags.NOUN, tags.ADJ}),
    voice_final=True,  # kitaplık -> kitaplığı (final k softens before a vowel)
)
D_CI = Suffix("ci", "CI", derivational=True, to_pos=tags.NOUN, applies_to=frozenset({tags.NOUN}))
# Diminutive / endearment -CIk (kitapçık, evcik, kuşçuk). The C archiphoneme hardens to ç
# after a voiceless consonant for free; ``voice_final`` softens the final k before a vowel
# (kitapçık -> kitapçığı, like -lIk). ``applies_to={NOUN}`` is the overgeneration guard: the
# rule never fires on an ADJ/ADV base (no *güzelcik, *sıcakçık) — the intensive-adjective
# diminutives (sıcacık, küçücük) reshape their stem unpredictably and are enumerated as
# IrregularForm exceptions instead, never generated by this edge.
D_CIK = Suffix(
    "cik",
    "CIk",
    derivational=True,
    to_pos=tags.NOUN,
    applies_to=frozenset({tags.NOUN}),
    voice_final=True,
)

#: Nominal-side derivations, appended after the inflectional edges so inflection-only
#: traversal order (and the guesser, which forbids derivation) is byte-identical to before.
#: -CIk is appended LAST so every pre-existing traversal prefix is unchanged.
_NOMINAL_DERIVATIONS = [D_LI, D_SIZ, D_LIK, D_CI, D_CIK]


# --- Verbal derivations (verb -> new nominal/adjectival stem) ------------------------
# Gated by graph position (only reachable from V_ROOT/V_NEG), so no applies_to is needed.
# verb -> noun:
VN_MA = Suffix("ma", "mA", derivational=True, to_pos=tags.NOUN)  # gelme (verbal noun / act)
VN_IS = Suffix("is", "(y)Iş", derivational=True, to_pos=tags.NOUN)  # geliş, yürüyüş
INF = Suffix("mak", "mAk", derivational=True, to_pos=tags.NOUN)  # gelmek (infinitive)
# verb -> adjective (participles):
PART_AN = Suffix(
    "an", "(y)An", derivational=True, to_pos=tags.ADJ, glide_raise=True
)  # gelen, diyen
PART_DIK = Suffix("dik", "DIk", derivational=True, to_pos=tags.ADJ, voice_final=True)  # bildiği
PART_ACAK = Suffix(
    "acak", "(y)AcAk", derivational=True, to_pos=tags.ADJ, voice_final=True, glide_raise=True
)  # gelecek, diyecek

#: Verb-side derivations that land in the shared N_DERIV nominal state (then inflect). The
#: infinitive -mAk is handled separately: it lands in the terminal V_INF (no case yet).
_VERBAL_DERIVATIONS_TO_NOMINAL = [VN_MA, VN_IS, PART_AN, PART_DIK, PART_ACAK]
