"""Derivational suffixes — a single, non-recursive derivation slot between root and inflection.

Nominal derivations (-lI, -sIz, -lIk, -CI, -CIk) turn a root/adjective into a new nominal
stem; verbal derivations (-mA, -(y)Iş, the participles -(y)An/-DIk/-(y)AcAk/-mIş, the aorist
participle -(A/I)r, the negative-aorist participle -mAz, and the infinitive -mAk) turn a verb
into a nominal one. Each is data-declared: ``derivational=True`` opens a boundary (its
``name`` is recorded under ``features[tags.DERIVATION]``), ``applies_to`` is the overgeneration
guard, and the graph position handles the verb-side gating. The wiring lives in
:mod:`.transitions`.
"""

from __future__ import annotations

from ...core import tags
from .suffix import Suffix

# --- Nominal derivations (root/adj -> new nominal stem) ------------------------------
# Data-declared: each carries no inflectional feature dict — its record is the derivation
# name appended to features[tags.DERIVATION]. ``applies_to`` is the overgeneration guard.

D_LI = Suffix("li", "lI", derivational=True, to_pos=tags.ADJ, applies_to=frozenset({tags.NOUN}))
D_SIZ = Suffix("siz", "sIz", derivational=True, to_pos=tags.ADJ, applies_to=frozenset({tags.NOUN}))
D_LIK = Suffix(
    "lik",
    "lIk",
    derivational=True,
    to_pos=tags.NOUN,
    applies_to=frozenset({tags.NOUN, tags.ADJ}),
    voice_final=True,  # kitaplık -> kitaplığı (final k softens before a vowel)
)
D_CI = Suffix("ci", "CI", derivational=True, to_pos=tags.NOUN, applies_to=frozenset({tags.NOUN}))
# Diminutive / endearment -CIk (kitapçık, evcik, kuşçuk). The C archiphoneme hardens to ç
# after a voiceless consonant for free; ``voice_final`` softens the final k before a vowel
# (kitapçık -> kitapçığı, like -lIk). ``applies_to={NOUN}`` is the overgeneration guard: the
# rule never fires on an ADJ/ADV base (no *güzelcik, *sıcakçık) — the intensive-adjective
# diminutives (sıcacık, küçücük) reshape their stem unpredictably and are enumerated as
# IrregularForm exceptions instead, never generated by this edge.
D_CIK = Suffix(
    "cik",
    "CIk",
    derivational=True,
    to_pos=tags.NOUN,
    applies_to=frozenset({tags.NOUN}),
    voice_final=True,
)

# Equative / adverbial -CA (güzelce "nicely", insanca "humanely", çocukça "childishly",
# aptalca "stupidly"). Turns a NOUN/ADJ into an ADVERB (its manner/equative reading). The C
# archiphoneme hardens to ç after a voiceless consonant for free (çocukça, kitapça), so that
# requirement needs no code. ``applies_to={NOUN, ADJ}`` is the overgeneration guard: it never
# fires on a NUM (*birce) or a VERB (*gelce, structurally unreachable anyway). It lands in the
# TERMINAL N_ADV_CA (no further inflection — no *güzelceyi/*güzelceler); the pronominal
# equatives (bence, sence) and the lexicalized language name türkçe are enumerated instead.
D_CA = Suffix(
    "ca", "CA", derivational=True, to_pos=tags.ADV, applies_to=frozenset({tags.NOUN, tags.ADJ})
)

# Relational -sAl (toplumsal "societal", tarihsel "historical", bölgesel "regional",
# kimyasal "chemical"). Turns a NOUN into an ADJECTIVE. ``applies_to={NOUN}`` blocks it on an
# ADJ (*güzelsel) or a VERB (*gelsel). Lands in the shared N_DERIV, so it inflects and hosts the
# ek-fiil for free (toplumsallar, toplumsaldır). The lexicalized kumsal (beach) is a whole-word
# NOUN entry so the kum+sal split stays a ranked alternative, never the primary.
D_SAL = Suffix("sal", "sAl", derivational=True, to_pos=tags.ADJ, applies_to=frozenset({tags.NOUN}))

#: Nominal-side derivations, appended after the inflectional edges so inflection-only
#: traversal order (and the guesser, which forbids derivation) is byte-identical to before.
#: -CIk is appended before the new -CA/-sAl so every pre-existing traversal prefix is unchanged;
#: -CA/-sAl are appended LAST (in that order). -CA targets the terminal N_ADV_CA, so it is wired
#: positionally in :mod:`.transitions` rather than through this shared N_DERIV list; -sAl lands
#: in N_DERIV like the other nominal derivations, so it is the only new member of this list.
_NOMINAL_DERIVATIONS = [D_LI, D_SIZ, D_LIK, D_CI, D_CIK, D_SAL]

#: The first-level nominal derivations that may host ONE further -lIk (gazete+ci+lik,
#: ev+siz+lik, ev+li+lik). Kept in DATA (not a hardcoded branch) per the rules-in-data
#: contract: a stackable derivation lands in ``N_DERIV_LIK_HOST`` instead of plain ``N_DERIV``,
#: and that host's only extra edge is -lIk back into plain ``N_DERIV`` (which re-derives nothing),
#: bounding the second slot at depth two. Deliberately excludes the diminutive -CIk, the
#: relational -sAl (toplumsallık deferred, correctness over coverage), and -lIk itself
#: (*kitaplıklık) — so widening/narrowing the productive set is a one-line data change here.
#: A tuple (not a set): :class:`Suffix` is an unhashable dataclass, and membership testing over
#: the six-element ``_NOMINAL_DERIVATIONS`` is trivial; each member is a distinct singleton, so
#: ``s in _LIK_STACKABLE`` (dataclass equality) selects exactly these three.
_LIK_STACKABLE = (D_LI, D_SIZ, D_CI)


# --- Relative / pronominal -ki (evdeki, benimki, dünkü) ------------------------------
# The relative -ki turns a locative/genitive nominal (or a temporal noun/adverb) into an
# ADJ/pronominal "the one that is (at/of) X". It is DERIVATIONAL (records the name "ki") and,
# crucially, does NOT harmonize — the template is the literal lowercase "ki", so evdeki/masadaki
# never become *evdekı by construction (the sole exception is the rounded temporal allomorph -kü
# after dün/bugün, a per-word lexical fact carried by a separate edge, NOT a harmony rule). Every
# -ki edge lands in N_KI, which declines the result like a pronoun (buffer-n: evdekini).

#: Relative -ki after a locative/genitive case (evdeki, masadaki, evindeki, evinki, kiminki).
#: Unrestricted (no ``applies_to``): it is reachable ONLY from N_CASE_LG, which a verb never
#: reaches, so its scope is already exactly "any locative/genitive nominal".
KI = Suffix("ki", "ki", derivational=True, to_pos=tags.ADJ)
#: Pronominal -ki on a genitive/locative pronoun HOST (benimki, seninki, onunki, ondaki). Same
#: literal "ki"; to_pos=PRON (the result is a pronoun). Reachable only from KI_HOST_ROOT.
KI_PRON = Suffix("ki", "ki", derivational=True, to_pos=tags.PRON)
#: Temporal -ki root-adjacent on a temporal noun/adverb (yarınki, sabahki, akşamki, şimdiki,
#: sonraki, önceki). ``applies_to={NOUN, ADV}`` + ``requires_attribute="temporal"`` gate it to
#: the curated temporal words only (no *evki). Literal "ki" (unrounded).
KI_TEMP = Suffix(
    "ki",
    "ki",
    derivational=True,
    to_pos=tags.ADJ,
    applies_to=frozenset({tags.NOUN, tags.ADV}),
    requires_attribute="temporal",
)
#: The ROUNDED temporal allomorph -kü (dünkü, bugünkü). This is a per-word LEXICAL fact (dün/
#: bugün take -kü; yarın/sabah keep -ki; onunki keeps -ki after u), NOT a phonological harmony
#: rule — so it is a separate edge gated by ``requires_attribute="temporal_rounded"``, with the
#: literal "kü" template. A vowel-based rule would wrongly give *onunkü/*dünki.
KU_TEMP = Suffix(
    "ki",
    "kü",
    derivational=True,
    to_pos=tags.ADJ,
    applies_to=frozenset({tags.NOUN, tags.ADV}),
    requires_attribute="temporal_rounded",
)
#: The two root-adjacent temporal -ki/-kü edges (appended LAST to N_ROOT in :mod:`.transitions`).
_TEMPORAL_KI = [KI_TEMP, KU_TEMP]


# --- Denominal verbalizers (NOUN/ADJ -> VERB) ----------------------------------------
# -lA / -lAn / -lAş turn a noun or adjective into a VERB stem that then takes the FULL verbal
# inflection (tense, negation, mood, the verb->nominal derivations, converbs) — taş->taşla-,
# temiz->temizle-, ev->evlen-, süs->süslen-, güzel->güzelleş-, selam->selamlaş-. Each is
# DERIVATIONAL (its ``name`` is recorded under features[tags.DERIVATION]; the lemma stays the
# base noun/adjective) and DOUBLE-guarded against overgeneration exactly like the reciprocal /
# temporal-ki precedent:
#   * ``applies_to={NOUN, ADJ}`` blocks a NUM/PRON base structurally (no *birle-, and a VERB
#     base is unreachable — these hang only off N_ROOT);
#   * ``requires_attribute`` gates each to a CURATED per-base list declared in the lexicon
#     (verbalizer_la / verbalizer_lan / verbalizer_las), so -lAş/-lAn fire only on plausible
#     bases and no common word is flooded.
# Because they are ``derivational=True``, the guesser (``allow_derivation=False``) never walks
# them — zero OOV impact. They are root-adjacent (only on N_ROOT), so ``requires_attribute`` is
# checked against the root's own attributes, and re-derivation is structurally impossible (a
# derived stem lands in N_DERIV, which carries no verbalizer edge: no *güzellikleş-). They land
# in the NON-final V_DENOM (see states/transitions), so a bare denominal stem is not accepted
# (taşla stays taş+instrumental; the bare imperative temizle!/selamlaş! is deferred).
D_V_LA = Suffix(
    "la",
    "lA",
    derivational=True,
    to_pos=tags.VERB,
    applies_to=frozenset({tags.NOUN, tags.ADJ}),
    requires_attribute="verbalizer_la",
)
D_V_LAN = Suffix(
    "lan",
    "lAn",
    derivational=True,
    to_pos=tags.VERB,
    applies_to=frozenset({tags.NOUN, tags.ADJ}),
    requires_attribute="verbalizer_lan",
)
D_V_LAS = Suffix(
    "las",
    "lAş",
    derivational=True,
    to_pos=tags.VERB,
    applies_to=frozenset({tags.NOUN, tags.ADJ}),
    requires_attribute="verbalizer_las",
)
#: The three denominal verbalizer edges (appended LAST to N_ROOT in :mod:`.transitions`, all
#: landing in V_DENOM). Kept in DATA so widening/narrowing the productive set is a data change.
_DENOMINAL_VERBALIZERS = [D_V_LA, D_V_LAN, D_V_LAS]


# --- Verbal derivations (verb -> new nominal/adjectival stem) ------------------------
# Gated by graph position (only reachable from V_ROOT/V_NEG), so no applies_to is needed.
# verb -> noun:
VN_MA = Suffix("ma", "mA", derivational=True, to_pos=tags.NOUN)  # gelme (verbal noun / act)
VN_IS = Suffix("is", "(y)Iş", derivational=True, to_pos=tags.NOUN)  # geliş, yürüyüş
INF = Suffix("mak", "mAk", derivational=True, to_pos=tags.NOUN)  # gelmek (infinitive)
# verb -> adjective (participles / sıfat-fiil). Every participle carries verbform=participle so
# the inventory is uniformly queryable AND each is distinguished from the homographous finite
# tense it shares a surface with (the -mIş participle vs the finite evidential; the aorist
# participle vs the finite aorist). All keep the verb lemma/stem and inflect nominally after.
_PARTICIPLE = {tags.VERBFORM: "participle"}
PART_AN = Suffix(
    "an", "(y)An", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ, glide_raise=True
)  # gelen, diyen
PART_DIK = Suffix(
    "dik", "DIk", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ, voice_final=True
)  # bildiği
PART_ACAK = Suffix(
    "acak",
    "(y)AcAk",
    dict(_PARTICIPLE),
    derivational=True,
    to_pos=tags.ADJ,
    voice_final=True,
    glide_raise=True,
)  # gelecek, diyecek
# -mIş participle (completed-action adjective: geçmiş, pişmiş, okunmuş). DISTINCT from the finite
# evidential -mIş (verb_suffixes.EVID, {evidential: True}) — the two feature dicts are kept
# disjoint so the participle never masquerades as finite. Consonant-initial, so no glide_raise;
# the ş takes no final voicing. It joins the shared verb->nominal list, so it fires from the bare
# root, negation (gelmemiş), ability, and every voice state (okunmuş, kırılmış) exactly as -(y)An.
PART_MIS = Suffix("mis", "mIş", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ)

# Aorist participle -(A/I)r (akar su, güler yüz, biter): REUSES the lexically-irregular aorist
# allomorph machinery — three edges sharing the name "ar", each guarded by ``aorist_class``
# against the root's own class exactly like the finite aorist (verb_suffixes._AORISTS). de/ye are
# class "r" (der/yer: consonant-attached -r, no raising), so no glide_raise is needed.
PART_AOR_R = Suffix(
    "ar", "r", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ, aorist_class="r"
)  # okur, yürür
PART_AOR_AR = Suffix(
    "ar", "Ar", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ, aorist_class="Ar"
)  # akar, yapar
PART_AOR_IR = Suffix(
    "ar", "Ir", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ, aorist_class="Ir"
)  # gelir, oturur
#: The three class-guarded aorist-participle edges (bare root), parallel to ``_AORISTS``.
_PART_AORISTS = [PART_AOR_R, PART_AOR_AR, PART_AOR_IR]
#: Post-*voice* aorist participle: a voiced stem is always consonant-final, so its aorist is the
#: deterministic -Ir regardless of the root's class (okunur, görülür), carrying no aorist_class —
#: exactly like the finite AOR_VOICE. Never fires for a guess (derivational + no synthetic voice).
PART_AOR_VOICE = Suffix("ar", "Ir", dict(_PARTICIPLE), derivational=True, to_pos=tags.ADJ)

# Negative aorist participle -mAz (bitmez, çıkmaz, tükenmez, geçmez): the participle counterpart
# of the finite negative aorist. Carries the accrued polarity=negative (nominal acceptance keeps
# it, like gelmeyen) plus verbform, but NOT tense — a participle is not finite. It is wired
# positionally (transitions._root_continuation), NOT via _VERBAL_DERIVATIONS_TO_NOMINAL, so it
# never fires from V_NEG (no *gelmemez, mirroring the finite negative-aorist gap). It also lands
# in a DEDICATED state (N_PART_NEG, case-only), not the shared N_DERIV: the possessive/copula -Im
# / -Iz it would otherwise take there revive the deliberately-defective finite persons
# (*gelmezim / *gelmeziz), so the negative-aorist participle is kept adjectival (see transitions).
PART_MAZ = Suffix(
    "maz",
    "mAz",
    {tags.POLARITY: "negative", tags.VERBFORM: "participle"},
    derivational=True,
    to_pos=tags.ADJ,
)

#: Verb-side derivations that land in the shared N_DERIV nominal state (then inflect). The
#: infinitive -mAk is handled separately: it lands in the terminal V_INF (no case yet). PART_MIS
#: is appended LAST so every pre-existing traversal prefix is byte-stable. The aorist participle
#: (-(A/I)r) and PART_MAZ are NOT here — they are wired positionally in :mod:`.transitions` to
#: mirror the finite aorist / negative-aorist scope exactly (no aorist participle from V_NEG).
_VERBAL_DERIVATIONS_TO_NOMINAL = [VN_MA, VN_IS, PART_AN, PART_DIK, PART_ACAK, PART_MIS]


# --- Converbs / zarf-fiil (verb -> ADVERB) -------------------------------------------
# Adverbial verb forms: gelerek, gelip, gelince, geleli, geldikçe (from the root / a voiced
# stem / negation) plus the privative gelmeden, gelmeksizin (one negative-shaped morpheme on
# the bare root) and, on a finished tense, -ken (gelirken). Modelled exactly on _PARTICIPLE:
# each is derivational=True (its ``name`` is recorded under features[tags.DERIVATION]),
# to_pos=ADV, and carries verbform=converb so the whole converb inventory is uniformly
# queryable and distinct from the homographous finite tense a surface may share (gelmez the
# finite negative-aorist vs gelmezken the converb). Every converb keeps the verb lemma/stem
# and is TERMINAL — it lands in ADV_CVB (see states/transitions), taking no further inflection.
_CONVERB = {tags.VERBFORM: "converb"}

# -(y)ArAk (gelerek, okuyarak, yaparak, diyerek): A-initial, so glide_raise like PART_AN/FUT
# (de -> diyerek). The (y) buffer covers the vowel-final stem (okuyarak).
CVB_ARAK = Suffix(
    "arak", "(y)ArAk", dict(_CONVERB), derivational=True, to_pos=tags.ADV, glide_raise=True
)
# -(y)Ip (gelip, yapıp, okuyup): sequential converb. NO glide_raise — deyip is the TDK-standard
# form (diyip is a well-known common misspelling), so -(y)Ip mirrors the repo's unflagged
# -(y)Iş -> deyiş / -(y)IncA -> deyince precedent (a per-suffix flag cannot raise ye- alone
# while leaving de- unraised — raised_form is per-root — so the corresponding yiyip is
# deferred rather than shipping the wrong diyip; see the xfail below).
CVB_IP = Suffix("ip", "(y)Ip", dict(_CONVERB), derivational=True, to_pos=tags.ADV)
# -(y)IncA (gelince, okuyunca, deyince): "when/as soon as". NO glide_raise — deyince is the
# uncontested standard form (mirrors the repo's unflagged -(y)Iş -> deyiş precedent).
CVB_INCA = Suffix("inca", "(y)IncA", dict(_CONVERB), derivational=True, to_pos=tags.ADV)
# -(y)AlI (geleli, yapalı, diyeli): "since (V-ing)". A-initial, so glide_raise (de -> diyeli).
CVB_ALI = Suffix(
    "ali", "(y)AlI", dict(_CONVERB), derivational=True, to_pos=tags.ADV, glide_raise=True
)
# -DIkçA (geldikçe, yaptıkça, okudukça): "as long as / the more". Consonant-initial (no glide
# raise); no voice_final needed — ADV_CVB is terminal, nothing follows to soften a final stop.
CVB_DIKCE = Suffix("dikce", "DIkçA", dict(_CONVERB), derivational=True, to_pos=tags.ADV)
# -mAdAn (gelmeden, yapmadan "without V-ing"): ONE privative morpheme on the BARE root, not
# NEG + something separable (its shape mirrors PART_MAZ's). polarity=negative because it is
# privative. Wired on the root / voiced stems only, NOT V_NEG (no *gelmemeden double negative).
CVB_MADAN = Suffix(
    "madan",
    "mAdAn",
    {tags.POLARITY: "negative", **_CONVERB},
    derivational=True,
    to_pos=tags.ADV,
)
# -mAksIzIn (gelmeksizin, yapmaksızın "without V-ing"): the other privative converb, same
# scope and polarity as -mAdAn (root / voiced stems only, never V_NEG).
CVB_MAKSIZIN = Suffix(
    "maksizin",
    "mAksIzIn",
    {tags.POLARITY: "negative", **_CONVERB},
    derivational=True,
    to_pos=tags.ADV,
)
# -ken (gelirken, geliyorken, gelecekken, gelmezken): the temporal converb "while". UNLIKE the
# others it attaches to a FINITE stem (the aorist/progressive/future/evidential/necessitative,
# and the negative aorist), so it is wired onto V_T1 / V_AOR_NEG, not the root — see
# transitions. It does NOT harmonize (invariant "ken": gelirken, yaparken, koşarken), so the
# literal "ken" is lowercase; the (y) buffer only covers a vowel-final stem (gelmeliyken). No
# glide_raise (it never sits on a bare de-/ye- root). The nominal ek-fiil -(y)ken (evdeyken,
# güzelken) is OUT of scope this milestone and deliberately NOT wired into the copula layer.
CVB_KEN = Suffix("ken", "(y)ken", dict(_CONVERB), derivational=True, to_pos=tags.ADV)
# BUFFERLESS -ken for the STANDALONE substantive verb i- (iken, NOT *iyken): i- is vowel-final
# but takes no (y) buffer, so the shared CVB_KEN's "(y)ken" cannot be reused (it would realize
# iyken). Same converb closure as CVB_KEN (to_pos=ADV, verbform=converb, terminal in ADV_CVB);
# wired ONLY onto I_ROOT (see transitions.I_GRAPH). "ken" is invariant (no harmony), like CVB_KEN.
CVB_KEN_BARE = Suffix("ken", "ken", dict(_CONVERB), derivational=True, to_pos=tags.ADV)

#: Root/voiced-stem/-negation converbs (the -mAdAn/-mAksIzIn privatives are excluded from the
#: V_NEG set below — a double negative *gelmemeden is ungrammatical, mirroring PART_MAZ off
#: V_NEG). Wired positionally in :mod:`.transitions`, appended LAST so traversal prefixes stay
#: byte-stable.
_CONVERBS = [CVB_ARAK, CVB_IP, CVB_INCA, CVB_ALI, CVB_DIKCE, CVB_MADAN, CVB_MAKSIZIN]
#: The subset reachable from V_NEG (gelmeyerek, gelmeyip, gelmeyince, gelmeyeli, gelmedikçe):
#: the two privatives are dropped (see above).
_CONVERBS_FROM_NEG = [CVB_ARAK, CVB_IP, CVB_INCA, CVB_ALI, CVB_DIKCE]
